### ISSUE TITLE
Debian 12 (bookworm) 

### ISSUE THREAD

**Issue by dplatonoff** [arter97/immich-native#1]
Can't thank you enough for putting this together.

Made this to work on Debian stable with minimal effort.

## Install dependencies:

Additional dependency required: `apt install uuid-runtime`.

Debian provided Node 18 fails to build the web package with the notorious [sharp loading issue](https://github.com/lovell/sharp/issues/3870). Must install Node 20 (I used the [Nodesource repo](https://github.com/nodesource/distributions/wiki/Repository-Manual-Installation)).

Debian 12 does not offer pgvector for Postgres 15 (current stable). Use the [.deb package](http://apt.postgresql.org/pub/repos/apt/pool/main/p/pgvector/postgresql-15-pgvector_0.6.0-1.pgdg20.04+1_amd64.deb) from the Postgres repos.

## Other build issues

Installing systemd services fails because `sudo cp` asks for sudo password for immich
```shell
sudo cp immich*.service /etc/systemd/system/
sudo systemctl daemon-reload
for i in immich*.service; do
  sudo systemctl enable $i
  sudo systemctl start $i
done
```
The following worked for me
```shell
cp immich*.service /etc/systemd/system/
systemctl daemon-reload
for i in immich*.service; do
  sudo systemctl enable --now $i
done
```

Hope that helps other Debian users.

**Comment by arter97** [comment]
Thanks for the feedback and information!

I'll update the repo with the systemd fixes.

Didn't know that PostgreSQL provides pgvector themselves on the APT repository. I'll update to mention that too.

Btw, can't you just use PostgreSQL APT on Debian too? Seems like they provide one for Debian: https://www.postgresql.org/download/linux/debian/
