### ISSUE TITLE
Uploaded pictures appear broken

### ISSUE THREAD

**Issue by tgutzler** [arter97/immich-native#11]
Hi, when I upload pictures to immich-native, they all appear as broken image in the overview. This does not change when clicking on them to view the full-size image.

I have one unrelated error and one stating that there is a problem serving the image but nothing during upload. Maybe a permission problem?

/var/log/immich/immich-microservices.log:[Nest] 105  - 06/01/2024, 8:41:05 AM   ERROR [ImmichMicroservices] [MetadataService] Unable to initialize reverse geocoding: Error: ENOENT: no such file or directory, open '/var/lib/immich/resources/geodata-date.txt'
/var/log/immich/immich.log:[Nest] 62386  - 06/13/2024, 9:14:43 AM   ERROR [ImmichServer] [AssetServiceV1] Error serving IMAGE asset for web

**Comment by arter97** [comment]
This should've been fixed with the latest commits. Which revision did you use while installation?

**Comment by tgutzler** [comment]
I updated today and I can confirm that this is now fixed.

However, I had to install a new dependency: unzip

**Comment by arter97** [comment]
Surprised how many people don't have unzip already installed /shrug

Thanks for the note :)

**Comment by tgutzler** [comment]
I'm installing this in a dedicated lxc container of debian bookworm. So I'm starting from scratch with a fairly minimal system
