### ISSUE TITLE
Install Guide Missing Unzip Requirement - Geonames

### ISSUE THREAD

**Issue by rlkollman** [arter97/immich-native#12]
The new "Install Geonames" section has a requirement on zip/unzip that I don't see noted in the 'Other Apt Packages' portion of the readme file.  My installation of v1.106.4 (as an update from v1.105.2) failed at this section since I didn't have ZIP previously installed on Debian 12.

Obviously, `apt install zip` resolved the issue for me. Please update the readme/install guide to reflect this requirement.

Thank you for your continued great efforts keeping this package going for us! :)

**Comment by arter97** [comment]
Why on earth would a distro *not* ship with unzip though... lol

Are you sure Debian uses `zip` package to provide the unzip command? In Ubuntu, this is packaged under `unzip`, not `zip`. I'm not sure if adding this on a README is necessary (more so given by the naming difference between Ubuntu and Debian); the error is pretty self-explanatory enough for the user to fix it themselves.

If Debian uses `unzip`, please let me know. I'll add it.

**Comment by rlkollman** [comment]
I believe the usual preferred compression tool in *nix is **tar**, so that would be my guess as to why it may not be shipped in some distros.  I will say, I just checked a clean Ubuntu 23.04 LXC container on Proxmox and it doesn't have zip or unzip installed by default, either.

You can install unzip in Debian and Ubuntu as well, but it does not install zip automatically.  However, if you install zip, unzip is automatically available. I agree, it's easy to remedy once you see the error, but if the solution is to rerun the install.sh file, this error occurs late in the installation, and is depressing having to restart that script knowing you were close to the end.  And yes, I know one could just look at the script and finish out the last few commands, but, I'm just playing devil's advocate for novice users :)

From my Ubuntu 23.04:
`# apt install zip`
`The following additional packages will be installed:`
`  unzip`
`The following NEW packages will be installed:`
`  unzip zip`

vs unzip only _suggests_ installing zip:
`# apt install unzip`
`Suggested packages:`
`  zip`
`The following NEW packages will be installed:`
`  unzip`

So, you can unpack zip files, but not create them.  Which, isn't necessary, most likely, but just showing the difference.

Thanks!
