### ISSUE TITLE
install script fails

### ISSUE THREAD

**Issue by Ondjultomte** [arter97/immich-native#14]
Running a fresh install of debian bookworm

`root@immich:/var# ./installim.sh
+ TAG=v1.108.0
+ IMMICH_PATH=/var/lib/immich
+ APP=/var/lib/immich/app
+ [[ krifag != \i\m\m\i\c\h ]]
+ for i in immich*.service
+ systemctl stop 'immich*.service'
+ systemctl disable 'immich*.service'
Glob pattern passed to disable, but globs are not supported for this.
Invalid unit name "immich*.service" escaped as "immich\x2a.service".
Failed to disable unit: Unit file immich\x2a.service does not exist.
+ true
+ mkdir -p /var/lib/immich
+ chown immich:immich /var/lib/immich
chown: invalid user: 'immich:immich'
`

**Comment by arter97** [comment]
install.sh is not standalone. It must be located at the same directory with *.service files, and must be executed from that directory.
