### ISSUE TITLE
Python version (3.9.2) is not allowed by the project (>=3.10,<4.0)

### ISSUE THREAD

**Issue by BartRoozen** [arter97/immich-native#19]
Hi! I've come quite far in the installation, but after "+ pip3 install poetry Collecting poetry" a bunch of python is processed and eventually I run into this error in red, and the install seems to stop:
```
Current Python version (3.9.2) is not allowed by the project (>=3.10,<4.0).
Please change python executable via the "env use" command.
```
Running 'python3 -V' returns 3.9.2 so I've tried [manually](https://ultahost.com/knowledge-base/install-python-on-debian/) installing python 3.12.2 and setting it to default with:
'ln -s /usr/local/bin/python3.12 /usr/local/bin/python', and now python -V returns 3.12.2, however I still get the same error. Any ideas what I'm missing? I'm trying to install on Debian 11. Cheers!

PS: The error refers to change the env, but I couldn't find any [variables](https://immich.app/docs/install/environment-variables/) to force a certain version of python. Also attempted to purge python 3.9.2 which didn't help.

**Comment by arter97** [comment]
Try changing `python3` from the script to `/usr/local/bin/python3.12` directly here: https://github.com/arter97/immich-native/blob/df80a44/install.sh#L92C1-L92C8

The virtualenv should use 3.12 then.

With that said though, I think the system itself might be too old for Immich to properly operate (ffmpeg, imagemagick, etc).

**Comment by BartRoozen** [comment]
Hey thanks! I got past the Python error and the install script finished just fine. But, as you guessed, it won't start. I picked Bullseye because I [read](`https://github.com/arter97/immich-native/issues/1) that pgvector didn't work in Bookworm but on second thought, I'll give it another go in a fresh installation :) appreciate the quick response!
