### ISSUE TITLE
change upload location

### ISSUE THREAD

**Issue by divemasterjm** [arter97/immich-native#2]
Can you pleas etell me how to change upload location, i've tried changing env file but no results
thanks

**Comment by arter97** [comment]
You can simply symlink the directory you want to use to /var/lib/immich/upload, which is how I'm using it:

```
root@arter97-server:/var/lib/immich# ls -al
total 19
drwx------  5 immich immich 3488 Mar 12 02:16 .
drwxr-xr-x 83 root   root   3488 Mar  2 02:15 ..
drwxrwxr-x  8 immich immich 3488 Mar 12 02:16 app
drwxrwxr-x  4 immich immich 3488 Mar  2 02:41 cache
-rw-r--r--  1 immich immich  813 Mar  2 02:31 env
drwxrwxr-x  6 immich immich 3488 Mar 12 02:16 home
lrwxrwxrwx  1 immich immich   29 Mar 12 02:16 resources -> /var/lib/immich/app/resources
lrwxrwxrwx  1 immich immich   18 Mar  2 03:07 upload -> /zfs/immich/upload
```

Make sure your custom upload directory is also chown'ed by immich:immich.

**Comment by btecu** [comment]
I agree, setting in `IMMICH_MEDIA_LOCATION` is much better. Should add the variable to the ENV file?
