### ISSUE TITLE
1.100.0

### ISSUE THREAD

**Issue by Multigumi** [arter97/immich-native#3]
Since version 1.100.0, the update runs without errors, everything seems to work, but immich is not available. Unfortunately, I'm not that good at it, but does it work for anyone else, just not me? What should I check?

root@Immich-uj:~# systemctl status  immich
* immich.service - immich server
     Loaded: loaded (/etc/systemd/system/immich.service; enabled; preset: enabled)
     Active: active (running) since Sun 2024-04-07 14:13:59 UTC; 4min 17s ago
       Docs: https://github.com/immich-app/immich
   Main PID: 109 (immich_server)
      Tasks: 11 (limit: 18960)
     Memory: 155.6M
        CPU: 3.315s
     CGroup: /system.slice/immich.service
             `-109 immich_server

Apr 07 14:13:59 Immich-uj systemd[1]: Started immich.service - immich server.
root@Immich-uj:~# systemctl status  immich-microservices.service 
* immich-microservices.service - immich microservices
     Loaded: loaded (/etc/systemd/system/immich-microservices.service; enabled; preset: enabled)
     Active: active (running) since Sun 2024-04-07 14:13:59 UTC; 4min 27s ago
       Docs: https://github.com/immich-app/immich
   Main PID: 108 (immich_microser)
      Tasks: 11 (limit: 18960)
     Memory: 149.2M
        CPU: 3.169s
     CGroup: /system.slice/immich-microservices.service
             `-108 immich_microservices

Apr 07 14:13:59 Immich-uj systemd[1]: Started immich-microservices.service - immich microservices.
root@Immich-uj:~# systemctl status  immich-m                     
immich-machine-learning.service  immich-microservices.service     
root@Immich-uj:~# systemctl status  immich-machine-learning.service 
* immich-machine-learning.service - immich machine-learning
     Loaded: loaded (/etc/systemd/system/immich-machine-learning.service; enabled; preset: enabled)
     Active: active (running) since Sun 2024-04-07 14:13:59 UTC; 4min 35s ago
       Docs: https://github.com/immich-app/immich
   Main PID: 107 (gunicorn)
      Tasks: 4 (limit: 18960)
     Memory: 305.4M
        CPU: 2.004s
     CGroup: /system.slice/immich-machine-learning.service
             |-107 /var/lib/immich/app/machine-learning/venv/bin/python /var/lib/immich/app/machine-learning/venv/bin/gunicorn app.main:app -k app.config.CustomUvicornWorker -w 1 -b 127.0.0.1:3003 -t 120 --log-config-json log_conf.json --graceful-timeout 0
             `-329 /var/lib/immich/app/machine-learning/venv/bin/python /var/lib/immich/app/machine-learning/venv/bin/gunicorn app.main:app -k app.config.CustomUvicornWorker -w 1 -b 127.0.0.1:3003 -t 120 --log-config-json log_conf.json --graceful-timeout 0

Apr 07 14:13:59 Immich-uj systemd[1]: Started immich-machine-learning.service - immich machine-learning.

**Comment by rlkollman** [comment]
When you say 'it doesn't work', what do you mean? The status shows running, so are you unable to get to the web interface running on port 3001?

Was it running before updating to the 1.100.0 version, or is this a new install?

**Comment by Multigumi** [comment]
Yes, that's exactly the case.
version 1.99.0 ran perfectly before it, and if I downgrade to this version, it works again.

**Comment by rlkollman** [comment]
OK. I'm still running 1.98.0 as I don't want to break things, so I may not be able to help if it's an update issue.

1. Have you tried the latest 1.101.0?
2. Did you just change the tag in your local copy of install.sh or did you download a new copy of this repo (see notes below on change to install.sh)?

I noticed a change in install.sh between v1.99 and v1.100 on line 103 (not sure if this could be related to your issue):
https://github.com/arter97/immich-native/commit/2d4f468387c98dbb04db437be97f12f3e5b7a488
1.99 has:
sed -i -e "s@app.listen(port)@app.listen(port, '127.0.0.1')@g" $APP/dist/microservices/main.js
1.100 has:
sed -i -e "s@app.listen(port)@app.listen(port, '127.0.0.1')@g" $APP/dist/main.js

So, if you just used your existing local copy of install.sh, it would not have caught this change.

**Comment by Multigumi** [comment]
Yes, I also noticed this change, but it's definitely not a typo, because the 99.0 install.sh path doesn't work and the installation stops with an error.
So something really changed there, but I couldn't find in the documentation exactly what or why.
1.101.0 is exactly the same problem I have.
  Today I will try a completely fresh installation on another virtual machine.

**Comment by arter97** [comment]
Hmm. Maybe my local Node.js update changed some stuff.

Can you check find how many main.js are there in /var/lib/immich after you run install.sh?

**Comment by rlkollman** [comment]
Just for backwards reference, on v1.98, I have 2:
- /var/lib/immich/app/dist/main.js
- /var/lib/immich/app/dist/microservices/main.js

... and both contain very different content.

**Comment by Multigumi** [comment]
main.js file after /var/lib/immich:

root@Immich-uj-1-100-1:~# find /var/lib/immich/ -type f -name "main.js"
/var/lib/immich/app/node_modules/@nestjs/schematics/node_modules/jsonc-parser/lib/umd/main.js
/var/lib/immich/app/node_modules/@nestjs/schematics/node_modules/jsonc-parser/lib/esm/main.js
/var/lib/immich/app/node_modules/@nestjs/schematics/dist/lib/sub-app/files/js/src/main.js
/var/lib/immich/app/node_modules/@nestjs/schematics/dist/lib/application/files/js/src/main.js
/var/lib/immich/app/node_modules/jsonc-parser/lib/umd/main.js
/var/lib/immich/app/node_modules/jsonc-parser/lib/esm/main.js
/var/lib/immich/app/node_modules/dotenv/lib/main.js
/var/lib/immich/app/node_modules/human-signals/build/src/main.js
/var/lib/immich/app/node_modules/terser/main.js
/var/lib/immich/app/node_modules/resolve/test/module_dir/zmodules/bbb/main.js
/var/lib/immich/app/node_modules/resolve/test/resolver/without_basedir/main.js
/var/lib/immich/app/node_modules/resolve/test/pathfilter/deep_ref/main.js
/var/lib/immich/app/node_modules/resolve/test/precedence/bbb/main.js
/var/lib/immich/app/node_modules/resolve/test/precedence/aaa/main.js
/var/lib/immich/app/node_modules/tsconfig-paths-webpack-plugin/temp/main.js
/var/lib/immich/app/node_modules/@mapbox/node-pre-gyp/lib/main.js
/var/lib/immich/app/node_modules/dotenv-expand/lib/main.js
/var/lib/immich/app/node_modules/utimes/dist/main.js
/var/lib/immich/app/node_modules/bullmq/dist/esm/classes/main.js
/var/lib/immich/app/node_modules/bullmq/dist/cjs/classes/main.js
/var/lib/immich/app/dist/main.js

**Comment by arter97** [comment]
Everything seems to be in order.

Can you check /var/log/immich? All logs are redirected there.
Also, please post `sudo lsof -i | grep 300` output.

**Comment by Multigumi** [comment]
immich-machine-learning.log immich.log no errors

**Comment by arter97** [comment]
Seems like it's running properly. How are you accessing it? Since it's only listening on localhost:3001, you need to use a reverse proxy to use it on other devices.

https://immich.app/docs/administration/reverse-proxy/

**Comment by Multigumi** [comment]
these errors are also present in the working 1.99.0 log.

**Comment by arter97** [comment]
If you're referencing to the geofence errors, it has always been that case afaik.

For localhost listening, see commit a089567e6937541eeebcfb1467e10b959d53eb00. Make sure you understand what you're doing. I highly recommend using an https proxy, even on local networks.

I think that's what your issue is. Feel free to open this back up if it's not.

**Comment by Multigumi** [comment]
Thanks for the help! Now it is working :) .

**Comment by dplatonoff** [comment]
@arter97 please consider a less rigid way of forcing localhost binding in the installer. There are configurations where it's not desirable - e.g. if the reverse proxy runs on a different host or network appliance. Patching the install script on every update to avoid localhost binding is counter productive.

Thanks for keeping up with immich releases :)

**Comment by arter97** [comment]
> There are configurations where it's not desirable - e.g. if the reverse proxy runs on a different host or network appliance. 

Valid point, but on those cases, the user will know exactly where to look at and I believe current README states it well with an easy revert: simply commenting out a single `sed` command.

Your photo library should be very foolproof when it comes to security, and I believe listening only to localhost and forcing users to setup a reverse proxy is very desirable.
