### ISSUE TITLE
Is there a License for the project?

### ISSUE THREAD

**Issue by loeeeee** [arter97/immich-native#5]
Thanks @arter97 for this awesome project. Right now, I almost managed to get Immich working on my  Ubuntu 22.04 LTS LXC with GPU passthrough. However, I met some road blocks when using the script in the project, and I would like to contribute to project to make it more refined.

So, is there any plan to add a license to the project so I could properly make contribution to the project? 😀

**Comment by arter97** [comment]
I don't think applying a licensing on such a project makes sense. Everything on here are combination of well-known scripting practices. This entire repo could be a gist for all I care, but gist's single-file architecture seemed too limiting. Applying license here is equivalent to applying a license on your first CS major's "print hello world" homework.

**Comment by loeeeee** [comment]
Thanks for the reply!

Does this mean I could use this script and write a guide for LXC installation based-on that?

**Comment by arter97** [comment]
Of course, do whatever you please.

I want to give this WTFPL for all I care, I just don't think it makes sense to go that route when the software it's installing has a dedicated license (AGPL).
