### ISSUE TITLE
How to change listen IP or port

### ISSUE THREAD

**Issue by tgutzler** [arter97/immich-native#7]
Hi,
Great work getting this project up.
Following the instructions I only found one thing missing. You never apt install build-essentials, which leads to a build error half way through install.sh.

Once built, I tried to change the listen address by defining IMMICH_HOST=1.2.3.4 in the env file and restarting the immich service. I can see in the log file that the service restarts but it keeps only listening to 127.0.0.1. Same thing for IMMICH_PORT. What am I missing?

**Comment by arter97** [comment]
Sorry for the late reply.

I believe IMMICH_HOST is a Docker-specific configuration, which is why it's ignored in this native version.
See install.sh's "Use 127.0.0.1" part and try manually changing them.

And thanks for the build-essentials dep.
