### ISSUE TITLE
geodata-date.txt is missing

### ISSUE THREAD

**Issue by AlexandarY** [arter97/immich-native#8]
Hey,

After deploying Immich with the steps and scripts provided in this repository (big thanks! awesome job!) I noticed the following error in the `/var/log/immich/immich-microservices.log`

```
ERROR [MetadataService] Unable to initialize reverse geocoding: Error: ENOENT: no such file or directory, open '/usr/src/resources/geodata-date.txt'
```

After some poking around, I found [this bug](https://github.com/immich-app/immich/issues/5437) opened in the immich repo. As per [this](https://github.com/immich-app/immich/issues/5437#issuecomment-1836935833) response, the following 3 lines setup the GeoData bits in the containers ([link to code](https://github.com/immich-app/base-images/blob/main/server/Dockerfile#L58C1-L60C109):

```
ADD https://download.geonames.org/export/dump/cities500.zip /usr/src/resources/cities500.zip
ADD --chmod=444 https://download.geonames.org/export/dump/admin1CodesASCII.txt /usr/src/resources/admin1CodesASCII.txt
ADD --chmod=444 https://download.geonames.org/export/dump/admin2Codes.txt /usr/src/resources/admin2Codes.txt
```

I think these are missing from the `install.sh` and might be good to have them?

**Comment by arter97** [comment]
Yup, this should be fixed.

Moved to #10
